title: "さくらのクラウドのモニタリングスイートにotelcolで送信する本"
summary: "モニタリングスイートにotelcolから送信する方法について解説します"
type: "tech"
topics: ["さくらのクラウド"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - metrics-hostmetrics
  - metrics-otlp
  - logs-docker
  - logs-nginx

